version: '3.8'

services:
  karakeep-homedash:
    image: ghcr.io/codejawn/karakeep-homedash:latest
    container_name: karakeep-homedash
    ports:
      - "8595:8595"
    volumes:
      # Mount config directory for persistence
      - ./config:/app/config
    restart: unless-stopped